### ISSUE TITLE
[question]how to swipe begin by code

### ISSUE THREAD

**Issue by sugitatestblue** [touchlane/SlideController#75]
Could you tell me how to set `SlideController` to swipe begin event by code?

**Comment by VadzimMarozau** [comment]
Hello @sugitatestblue 
You can use `func shift(pageIndex: Int, animated: Bool = default, forced: Bool = default)`. It slides content to page at `pageIndex`.
If you want to handle swipe events initiated by user you need to implement protocol `SlidePageLifeCycle`. Please take a look on example project for more information.

**Comment by VadzimMarozau** [comment]
Archive issue
